# Wikibase for testing
version: '3'

services:
  wikibase:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - "80:80"
    volumes:
      - quickstatements-data:/quickstatements/data
      - ./quickstatements/extra-install.sh:/extra-install.sh
      - ./quickstatements/oauth.ini:/templates/oauth.ini
    networks:
      default:
        aliases:
         - wikibase.svc
         - ${WIKIBASE_HOST}
    environment:
      - DB_SERVER=mysql.svc:3306
      - MW_ADMIN_NAME=${MW_ADMIN_NAME}
      - MW_ADMIN_PASS=${MW_ADMIN_PASS}
      - MW_ADMIN_EMAIL=admin@example.com
      - MW_WG_SECRET_KEY=${MW_SECRET_KEY}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=my_wiki
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
      - MW_SERVER=https://${WIKIBASE_HOST}
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=${QS_PUBLIC_SCHEME_HOST_AND_PORT}
  mysql:
    image: mariadb:10.3
    restart: always
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - mysql.svc
  wdqs-frontend:
    image: "${QUERYSERVICE_UI_IMAGE_NAME}"
    restart: always
    ports:
    # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
     - "8834:80"
    links:
      - wdqs
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=${WIKIBASE_HOST}
      - WDQS_HOST=wdqs-proxy.svc
  wdqs:
    image: "${QUERYSERVICE_IMAGE_NAME}"
    restart: always
    command: /runBlazegraph.sh
    volumes:
      - query-service-data:/wdqs/data
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=${WIKIBASE_HOST}
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    restart: always
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  elasticsearch:
    image: "${ELASTICSEARCH_IMAGE_NAME}"
    restart: always
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  wdqs-updater:
    image: "${QUERYSERVICE_IMAGE_NAME}"
    restart: always
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=${WIKIBASE_HOST}
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
  quickstatements:
    image: "${QUICKSTATEMENTS_IMAGE_NAME}"
    restart: always
    volumes:
      - quickstatements-data:/quickstatements/data
      - ../quickstatements/wait-for-it.sh:/wait-for-it.sh
      - ./quickstatements/wait-entrypoint.sh:/wait-entrypoint.sh
    entrypoint: /bin/bash
    command: /wait-entrypoint.sh
    ports:
      - "8840:80"
    depends_on:
      - wikibase
    networks:
      default:
        aliases:
         - ${QS_HOST}
    environment:
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=${QS_PUBLIC_SCHEME_HOST_AND_PORT}
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=${WB_PUBLIC_SCHEME_HOST_AND_PORT}
      - WIKIBASE_SCHEME_AND_HOST=http://${WIKIBASE_HOST}
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"
      - OAUTH_CONSUMER_KEY=${OAUTH_CONSUMER_KEY}
      - OAUTH_CONSUMER_SECRET=${OAUTH_CONSUMER_SECRET}

volumes:
  LocalSettings:
  quickstatements-data:
  query-service-data:
  mediawiki-mysql-data:
